# -*- coding: utf-8 -*-
"""OCTO_komplet_3_06_AUT_ORS_OSRM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1as-XaDfuUdYf5FmAt4QQOJ8xcsQwzgoE

**Automatické načtení souborů z Disku Google OCTO komplet3.06 AUT ORS OSRM**
"""

from google.colab import drive
import os
import shutil

# Mount Google Drive
drive.mount('/content/drive')

# Define source and destination
source_folder = '/content/drive/MyDrive/HVB'
files_to_copy = ['obce01.csv', 'Makléři.xlsx', 'Export výstup.txt']

print("Copying files from Drive...")
for f in files_to_copy:
    src = os.path.join(source_folder, f)
    if os.path.exists(src):
        shutil.copy(src, '/content/')
        print(f"✅ {f} copied.")
    else:
        print(f"❌ {f} not found in {source_folder}")

"""**Export**"""

import pandas as pd
import re
import unicodedata
import os

def normalize_text(text):
    if pd.isna(text): return ""
    text = str(text).strip().lower()
    # Sjednocení oddělovačů (čárky/pomlčky) na mezery pro lepší vyhledávání
    text = text.replace('-', ' ').replace(',', ' ')
    text = unicodedata.normalize('NFKD', text).encode('ascii', 'ignore').decode('utf-8')
    text = text.replace('moravskoslezky', 'moravskoslezsky')
    return " ".join(text.split())

def get_kraj_from_text(norm_loc, obce_list):
    unique_kraje = set(o['kraj'] for o in obce_list)
    for k in unique_kraje:
        if re.search(r'\b' + re.escape(k) + r'\b', norm_loc.replace('kraj', '')):
            return k
    if "praha" in norm_loc and "okres praha" not in norm_loc: return "hlavni mesto praha"
    if "hlavni mesto praha" in norm_loc: return "hlavni mesto praha"
    unique_okresy = {o['okres']: o['kraj'] for o in obce_list}
    for okr, kr in unique_okresy.items():
        if re.search(r'\b' + re.escape(okr) + r'\b', norm_loc.replace('okres', '')): return kr
    for o in sorted(obce_list, key=lambda x: len(x['obec']), reverse=True):
        if re.search(r'\b' + re.escape(o['obec']) + r'\b', norm_loc): return o['kraj']
    return "Neznamy"

# Načtení základních dat
if os.path.exists('/content/obce01.csv'):
    df_obce = pd.read_csv('/content/obce01.csv', sep=';', encoding='utf-8')
    obce_list = [{'obec': normalize_text(r['Obec']), 'okres': normalize_text(r.get('Okres', '')), 'kraj': normalize_text(r.get('Kraj', ''))} for _, r in df_obce.iterrows()]

blocks = [] # Initialize blocks to an empty list
if os.path.exists('/content/Makléři.xlsx'):
    df_m_full = pd.read_excel('/content/Makléři.xlsx')
    makleri_info = []
    for _, r in df_m_full.iterrows():
        if pd.isna(r['Jméno']): continue
        makleri_info.append({'jmeno': str(r['Jméno']).strip(), 'kraj_norm': normalize_text(r.get('Kraj', ''))})

if os.path.exists('/content/Export výstup.txt'):
    with open('/content/Export výstup.txt', 'r', encoding='utf-8') as f:
        raw_content = f.read()
        blocks = [b.strip() for b in re.split(r'\n(?=\d+\.)', '\n' + raw_content) if b.strip()]
        if len(blocks) <= 1:
            blocks = [b.strip() for b in raw_content.split('\n\n') if b.strip()]

def find_best_coords(norm_loc, df_obce_sorted):
    target_kraj = get_kraj_from_text(norm_loc, obce_list)
    potential_matches = []
    for _, row in df_obce_sorted.iterrows():
        norm_obec = normalize_text(row['Obec'])
        # Robustnější hledání podřetězce
        if norm_obec in norm_loc:
            score = 0
            if normalize_text(row['Kraj']) == target_kraj: score += 10
            if normalize_text(row.get('Okres', '')) in norm_loc: score += 5
            potential_matches.append((score, [float(row['Longitude']), float(row['Latitude'])]))
    if potential_matches:
        return sorted(potential_matches, key=lambda x: x[0], reverse=True)[0][1]
    return None

print(f"Načteno {len(blocks)} inzerátů.")

"""**KRAJE**"""

ads_by_region = {}

for block in blocks:
    lines = block.split('\n')
    if lines:
        full_loc = re.sub(r'^[\d]+[\.\)]\s*', '', lines[0])
        norm_loc = normalize_text(full_loc)
        target_kraj_norm = get_kraj_from_text(norm_loc, obce_list)

        # Oprava: Odstranění duplicitního 'kraj' v názvu
        if target_kraj_norm == "hlavni mesto praha":
            final_kraj = "Hlavní Město Praha"
        elif target_kraj_norm == "Neznamy":
            final_kraj = "Neznámý"
        else:
            clean_name = target_kraj_norm.replace(' kraj', '').strip().title()
            final_kraj = f"{clean_name} kraj"

        if final_kraj not in ads_by_region:
            ads_by_region[final_kraj] = []
        ads_by_region[final_kraj].append(full_loc)

print("=== JMENOVITÝ SEZNAM INZERÁTŮ DLE KRAJŮ ===\n")
for kraj in sorted(ads_by_region.keys()):
    print(f"📍 {kraj}:")
    for i, ad in enumerate(sorted(ads_by_region[kraj]), 1):
        print(f"  {i}. {ad}")
    print("-" * 30)

"""### **Hlavní výpočet a Export (ORS)**
*Tato sekce obsahuje finální sjednocenou logiku pro výpočet silničních vzdáleností a uložení souboru `ORS_komplet.txt`.*
"""

import pandas as pd
import requests
import time
import re
import unicodedata
import os
from google.colab import userdata, files
from IPython.display import display, HTML, clear_output

ORS_API_KEY = userdata.get('ORS_API_KEY')
ORS_DELAY = 1.6

def normalize_text(text):
    if pd.isna(text): return ""
    text = str(text).strip().lower()
    # Sjednocení oddělovačů pro ORS buňku
    text = text.replace('-', ' ').replace(',', ' ')
    text = unicodedata.normalize('NFKD', text).encode('ascii', 'ignore').decode('utf-8')
    text = text.replace('moravskoslezky', 'moravskoslezsky')
    return " ".join(text.split())

def get_kraj_from_text(norm_loc, obce_list):
    unique_kraje = set(o['kraj'] for o in obce_list)
    for k in unique_kraje:
        if re.search(r'\b' + re.escape(k) + r'\b', norm_loc.replace('kraj', '')):
            return k
    if "praha" in norm_loc and "okres praha" not in norm_loc: return "hlavni mesto praha"
    if "hlavni mesto praha" in norm_loc: return "hlavni mesto praha"
    unique_okresy = {o['okres']: o['kraj'] for o in obce_list}
    for okr, kr in unique_okresy.items():
        if re.search(r'\b' + re.escape(okr) + r'\b', norm_loc.replace('okres', '')): return kr
    for o in sorted(obce_list, key=lambda x: len(x['obec']), reverse=True):
        if re.search(r'\b' + re.escape(o['obec']) + r'\b', norm_loc): return o['kraj']
    return "Neznamy"

def find_best_coords(norm_loc, df_obce_sorted):
    target_kraj = get_kraj_from_text(norm_loc, obce_list)
    potential_matches = []
    for _, row in df_obce_sorted.iterrows():
        norm_obec = normalize_text(row['Obec'])
        if norm_obec in norm_loc:
            score = 0
            if normalize_text(row['Kraj']) == target_kraj: score += 10
            if normalize_text(row.get('Okres', '')) in norm_loc: score += 5
            potential_matches.append((score, [float(row['Longitude']), float(row['Latitude'])]))
    if potential_matches:
        return sorted(potential_matches, key=lambda x: x[0], reverse=True)[0][1]
    return None

if 'df_obce' not in locals():
    df_obce = pd.read_csv('/content/obce01.csv', sep=';', encoding='utf-8')
obce_list = [{'obec': normalize_text(r['Obec']), 'okres': normalize_text(r.get('Okres', '')), 'kraj': normalize_text(r.get('Kraj', ''))} for _, r in df_obce.iterrows()]

if 'df_m_full' not in locals():
    df_m_full = pd.read_excel('/content/Makléři.xlsx')

if 'blocks' not in locals():
    with open('/content/Export výstup.txt', 'r', encoding='utf-8') as f:
        raw_content = f.read()
        blocks = [b.strip() for b in re.split(r'\n(?=\d+\.)', '\n' + raw_content) if b.strip()]
        if len(blocks) <= 1: blocks = [b.strip() for b in raw_content.split('\n\n') if b.strip()]

df_obce_sorted = df_obce.sort_values(by='Obec', key=lambda x: x.str.len(), ascending=False).copy()
makleri_db = []
for _, r in df_m_full.iterrows():
    if pd.isna(r['Jméno']): continue
    coords = None
    if pd.notna(r.get('Souřadnice')):
        try:
            c = str(r['Souřadnice']).replace(' ', '').split(',')
            if len(c) == 2:
                val1, val2 = float(c[0]), float(c[1])
                coords = [val2, val1] if 48 < val1 < 52 else [val1, val2]
        except: pass
    makleri_db.append({
        'jmeno': str(r['Jméno']).strip(),
        'kraj_norm': normalize_text(r.get('Kraj', '')),
        'pos': coords,
        'limit': float(r.get('Maximální vzdálenost od adresy (km)', 50)),
        'kapacita': int(r.get('Maximální počet výstupů', 10)) if pd.notna(r.get('Maximální počet výstupů')) else 10,
        'Byty': str(r.get('Byty', '')).lower() in ['ano', 'x', '1', 'true'],
        'Domy': str(r.get('Domy', '')).lower() in ['ano', 'x', '1', 'true'],
        'kontakt': str(r.get('Telefon', ''))
    })

final_results = []
distance_cache = {}
start_time = time.time()

for idx, block in enumerate(blocks, 1):
    elapsed = time.time() - start_time
    clear_output(wait=True)
    display(HTML(f'''<div style="padding:10px; border:1px solid #ddd; border-radius:5px; background:#f9f9f9;"><b>⏳ Probíhá výpočet: {idx} / {len(blocks)}</b><br>⏱ Čas: {int(elapsed // 60):02d}:{int(elapsed % 60):02d}</div>'''))
    lines = block.split('\n')
    if not lines: continue
    loc = re.sub(r"^[\d]+[\.\)]\s*", '', lines[0])
    norm_loc = normalize_text(loc)
    target_kraj = get_kraj_from_text(norm_loc, obce_list)
    found_coords = find_best_coords(norm_loc, df_obce_sorted)
    row = {'Inzerát': loc, 'Kraj': target_kraj}
    kraj_agents = [m for m in makleri_db if target_kraj in m['kraj_norm'] or (target_kraj == 'hlavni mesto praha' and 'praha' in m['kraj_norm'])]
    if found_coords and kraj_agents:
        for agent in kraj_agents:
            if not agent['pos']: continue
            cache_key = (tuple(found_coords), tuple(agent['pos']))
            if cache_key in distance_cache:
                row[f"{agent['jmeno']} (km)"] = distance_cache[cache_key]
            else:
                try:
                    # --- HYBRIDNÍ TRASOVÁNÍ (ORS -> FAILOVER OSRM S TIMEOUTEM 10s) ---
                    try:
                        res = requests.post('https://api.openrouteservice.org/v2/directions/driving-car',
                                           json={"coordinates": [found_coords, agent['pos']]},
                                           headers={'Authorization': ORS_API_KEY, 'Content-Type': 'application/json'},
                                           timeout=10)
                        if res.status_code == 200:
                            dist_km = round(res.json()['routes'][0]['segments'][0]['distance'] / 1000.0, 1)
                            distance_cache[cache_key] = dist_km
                            row[f"{agent['jmeno']} (km)"] = dist_km
                            time.sleep(ORS_DELAY)
                        else:
                            raise ValueError(f"ORS chyba: {res.status_code}")
                    except Exception as e:
                        try:
                            url = f"http://router.project-osrm.org/route/v1/driving/{found_coords[0]},{found_coords[1]};{agent['pos'][0]},{agent['pos'][1]}?overview=false"
                            res_osrm = requests.get(url, timeout=5)
                            if res_osrm.status_code == 200:
                                data = res_osrm.json()
                                if "routes" in data and len(data["routes"]) > 0:
                                    dist_km = round(data["routes"][0]["distance"] / 1000.0, 1)
                                    distance_cache[cache_key] = dist_km
                                    row[f"{agent['jmeno']} (km)"] = dist_km
                                else: row[f"{agent['jmeno']} (km)"] = "N/A"
                            else: row[f"{agent['jmeno']} (km)"] = "N/A"
                        except: row[f"{agent['jmeno']} (km)"] = "N/A"
                        time.sleep(0.1)
                except: row[f"{agent['jmeno']} (km)"] = "N/A"
    final_results.append(row)

df_export = pd.DataFrame(final_results)
df_export.insert(0, 'ID', range(1, len(df_export) + 1))
df_export.to_csv('ORS_komplet.txt', sep='\t', index=False, encoding='utf-8')
display(df_export.fillna('-'))

"""**Validace limitů a výstup pro navolávačku**

"""

def detect_type(text_blob):
    text = normalize_text(text_blob)
    house_keywords = ['rodinny dum', 'rd', 'chata', 'chalupa', 'vila', 'prodej domu', 'rodinneho domu']
    if any(x in text for x in house_keywords):
        return 'Domy'
    if any(x in text for x in ['pozemek', 'zahrada', 'parcela']):
        return 'Pozemky'
    if any(x in text for x in ['komerc', 'kancelar', 'sklad', 'prostor', 'objekt']):
        return 'Komerční'
    return 'Byty'

# Mapování URL a telefonů z původních bloků
url_map = {}
phone_map = {}
for block in blocks:
    lines = block.split('\n')
    if len(lines) > 0:
        loc_key = re.sub(r'^[\d]+[\.\)]\s*', '', lines[0]).strip()
        urls = re.findall(r'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+', block)
        if urls: url_map[loc_key] = urls[0]
        phone_match = re.search(r'(?:Tel|Tel\.|Telefon):?\s*(\+?\d[\d\s]{8,})', block, re.IGNORECASE)
        if phone_match: phone_map[loc_key] = phone_match.group(1).strip()

for m in makleri_db:
    m['aktualne_prirazeno'] = 0
    if m['jmeno'] in ['Manda', 'Nemes']:
        m['Byty'] = True
        m['Domy'] = True

final_vystup = []
filtered_out_info = []
# KLÍČOVÁ OPRAVA: Sledování unikátnosti obsahu inzerátu napříč všemi operátory
processed_ads_content = set()

if os.path.exists('ORS_komplet.txt'):
    df_in = pd.read_csv('ORS_komplet.txt', sep='\t')
    for _, row in df_in.iterrows():
        inzerat_text = str(row['Inzerát']).strip()
        # Vytvoření otisku inzerátu pro eliminaci duplicit (text + url pokud existuje)
        ad_url = url_map.get(inzerat_text, "")
        ad_fingerprint = f"{normalize_text(inzerat_text)}_{ad_url}"

        if ad_fingerprint in processed_ads_content:
            continue

        typ_nem = detect_type(inzerat_text)
        reasons = []
        vhodni_agenti = []
        agent_cols = [c for c in df_in.columns if '(km)' in c]

        for col in agent_cols:
            agent_name = col.replace(' (km)', '')
            dist = row[col]
            m_info = next((m for m in makleri_db if m['jmeno'] == agent_name), None)
            if pd.isna(dist) or dist == 'N/A': continue
            dist = float(dist)
            if not m_info: continue

            if not m_info.get(typ_nem):
                reasons.append(f"{agent_name}: Nepodporuje typ {typ_nem}.")
            elif dist > m_info['limit']:
                reasons.append(f"{agent_name}: Příliš daleko ({dist} km > {m_info['limit']} km).")
            elif m_info['aktualne_prirazeno'] >= m_info['kapacita']:
                reasons.append(f"{agent_name}: Kapacita plná ({m_info['kapacita']}/{m_info['kapacita']}).")
            else:
                vhodni_agenti.append({'m_ref': m_info, 'jmeno': agent_name, 'dist': dist, 'kontakt': m_info['kontakt']})

        if vhodni_agenti:
            vhodni_agenti.sort(key=lambda x: x['dist'])
            top = vhodni_agenti[0]

            # Označíme jako zpracované POUZE pokud jsme našli makléře
            processed_ads_content.add(ad_fingerprint)

            top['m_ref']['aktualne_prirazeno'] += 1
            actual_phone = phone_map.get(inzerat_text, "")

            phone_line = f"\nTel: {actual_phone}" if actual_phone else ""
            block_txt = f"{inzerat_text}{phone_line}\n~{top['dist']} km | {top['jmeno']} | {top['kontakt']}\n{ad_url}"
            final_vystup.append({'dist': top['dist'], 'text': block_txt})
        else:
            filtered_out_info.append({'ID': row.get('ID', 'N/A'), 'Inzerát': inzerat_text, 'Typ': typ_nem, 'Důvod': "; ".join(list(dict.fromkeys(reasons)))})

    final_vystup.sort(key=lambda x: x['dist'])
    with open('whatsapp_vystup_finalni.txt', 'w', encoding='utf-8') as f:
        for i, item in enumerate(final_vystup, 1):
            f.write(f"{i}. {item['text']}\n\n")

    print(f"✅ Hotovo. Exportováno {len(final_vystup)} unikátních zakázek. Duplicity byly odstraněny.")

"""### **Celkové shrnutí a statistiky**
Vytížení makléřů a distribuci inzerátů.
"""

import pandas as pd
import re
import numpy as np
import os

FINAL_VALIDATED_FILE = 'whatsapp_vystup_finalni.txt'

# 1. Analýza přiřazení
assigned_counts = {}
if 'final_vystup' in locals():
    for item in final_vystup:
        match = re.search(r'\|\s*([^|]+?)\s*\|', item['text'])
        if match:
            name = match.group(1).strip()
            assigned_counts[name] = assigned_counts.get(name, 0) + 1

# 2. Vytížení makléřů
summary_agents = []
for m in makleri_db:
    name = m['jmeno']
    if not name or name == "nan" or name == "": continue
    safe_count = assigned_counts.get(name, 0)
    safe_limit = m['kapacita'] if m['kapacita'] > 0 else 10
    utilization = (safe_count / safe_limit * 100)
    summary_agents.append(f"{name} | {safe_count} | {safe_limit} | {utilization:.1f}%")

# 3. Statistiky
geo_stats = {}
d_bins = {'0-15': 0, '15-30': 0, '30-50': 0, '50+': 0}

if 'final_vystup' in locals():
    for item in final_vystup:
        lines = item['text'].split('\n')
        loc_parts = lines[0].split(',')
        kraj_key = loc_parts[-1].strip() if loc_parts else "Neznámý"
        geo_stats[kraj_key] = geo_stats.get(kraj_key, 0) + 1

        d = item['dist']
        if d <= 15: d_bins['0-15'] += 1
        elif d <= 30: d_bins['15-30'] += 1
        elif d <= 50: d_bins['30-50'] += 1
        else: d_bins['50+'] += 1

total_processed = len(blocks) if 'blocks' in locals() else 0
total_exported = len(final_vystup) if 'final_vystup' in locals() else 0

print("=== Shrnutí : Vytížení makléřů ===")
print("Jméno | Přiřazeno | Limit | Využití %")
for line in summary_agents: print(line)

print("\n=== Inzeráty dle krajů ===")
for kraj_item, count_item in sorted(geo_stats.items(), key=lambda x: x[1], reverse=True):
    print(f"{kraj_item} | {count_item}")

print(f"\n=== Rozdělení dle vzdálenosti ===")
print(f"0-15 km: {d_bins['0-15']} | 15-30 km: {d_bins['15-30']} | 30-50 km: {d_bins['30-50']} | 50+ km: {d_bins['50+']}")

"""**Emailové shrnutí**"""

from datetime import datetime
import os

actual_total = total_processed if 'total_processed' in locals() else 0
actual_exported = total_exported if 'total_exported' in locals() else 0
actual_filtered = max(0, actual_total - actual_exported)

email_body = f"""Finální report a statistiky z dnešního zpracování realitních inzerátů.

Vzhledem k postupující automatizaci bude od zítřejšího dne finalizace reportu k dispozici pouze na níže uvedeném
webu s možností variantního zpracování:

1. zpracování na PC - přehlednější a intuitivnější (níže uvedený web si uložte pro každodenní zpracování)
2. zpracování na mobilním telefonu (stávající verze) - sdílejte (nebo kopírujte) data do Whatsapp
z webového rozhraní (pošlete sama sobě) a postupujte dle zvyklostí

Detailní rozbor (s možností sdílení WhatsApp a datem aktualizace) je k dispozici zde:
https://dna2026.github.io/HVB/Dashboard.html

S pozdravem,
Automatizovaný systém zpracování dat"""

with open('email_shrnuti.txt', 'w', encoding='utf-8') as f:
    f.write(email_body)

print("=== NÁHLED EMAILU S AKTIVNÍM ODKAZEM ===")
print(email_body)

"""### HTML Report s Mapou

"""

import folium
import pandas as pd
import re
import os

output_filename = 'mapa_zakazky.html'
m = folium.Map(location=[49.8, 15.5], zoom_start=8, tiles='cartodbpositron')

# Mapování přiřazení z final_vystup pro barvy
assigned_map = {}
for item in final_vystup:
    lines = item['text'].strip().split('\n')
    if not lines: continue
    raw_line = lines[0].strip()
    clean_key = re.sub(r'^[\d]+[\.\)]\s*', '', raw_line)
    match_agent = re.search(r'\|\s*([^|]*?)\s*\|', item['text'])
    if match_agent:
        assigned_map[clean_key] = match_agent.group(1).strip()
    else:
        assigned_map[clean_key] = "Ano"

# Vykreslení makléřů - seřazeno od největšího limitu po nejmenší
for agent in sorted(makleri_db, key=lambda x: x['limit'] if pd.notna(x['limit']) else 0, reverse=True):
    if agent['jmeno'] and agent['pos']:
        # Fialová ikona makléře
        folium.Marker(
            location=[agent['pos'][1], agent['pos'][0]],
            popup=f"<b>Makléř:</b> {agent['jmeno']}",
            icon=folium.Icon(color='purple', icon='user'),
            tooltip=f"Makléř: {agent['jmeno']} | Limit: {agent['limit']} km"
        ).add_to(m)

        # Kruh dosahu s tooltipem
        folium.Circle(
            location=[agent['pos'][1], agent['pos'][0]],
            radius=agent['limit'] * 1000,
            color='green', weight=2, fill=True, fill_opacity=0.06,
            tooltip=f"Dosah: {agent['jmeno']} ({agent['limit']} km)"
        ).add_to(m)

# Vykreslení inzerátů
if 'df_export' in locals():
    for _, row in df_export.iterrows():
        inzerat_text = str(row['Inzerát']).strip()
        clean_inzerat = re.sub(r'^[\d]+[\.\)]\s*', '', inzerat_text)
        coords = find_best_coords(normalize_text(inzerat_text), df_obce_sorted)
        if coords:
            agent_name = assigned_map.get(clean_inzerat) or assigned_map.get(inzerat_text)
            is_assigned = agent_name is not None
            dot_color = 'green' if is_assigned else 'red'
            status = f"Přiřazeno: {agent_name}" if is_assigned else "Odfiltrováno"
            ad_url = url_map.get(inzerat_text, url_map.get(clean_inzerat, ""))
            link_html = f'<a href="{ad_url}" target="_blank">{ad_url}</a>' if ad_url else "URL nenalezeno"
            folium.CircleMarker(
                location=[coords[1], coords[0]],
                radius=6,
                popup=folium.Popup(f"<b>{inzerat_text}</b><br>Stav: {status}<br>{link_html}", max_width=350),
                color=dot_color,
                fill=True,
                fill_opacity=0.8
            ).add_to(m)

with open(output_filename, 'w', encoding='utf-8') as f:
    f.write(m._repr_html_())

print(f"✅ Mapa {output_filename} aktualizována s opravenými tooltipy.")

import zipfile
from google.colab import files
import os

# Aktualizace ZIP archivu s opravenou mapou (aktivní odkazy)
files_to_zip = ['whatsapp_vystup_finalni.txt', 'mapa_zakazky.html', 'ORS_komplet.txt', 'email_shrnuti.txt']
zip_filename = 'vystup_komplet_final_v3.zip'

with zipfile.ZipFile(zip_filename, 'w') as zipf:
    for f in files_to_zip:
        if os.path.exists(f):
            zipf.write(f)

print(f"✅ Archiv aktualizován: {zip_filename}")

"""### **Finální stažení a odeslání**
Tato buňka zajistí stažení všech vytvořených souborů a zobrazí tlačítko pro Thunderbird.
"""

import os
import urllib.parse
from google.colab import files
from IPython.display import display, HTML
from google.colab import output
from datetime import datetime

# Refresh UI data
whatsapp_text = ""
if os.path.exists('whatsapp_vystup_finalni.txt'):
    with open('whatsapp_vystup_finalni.txt', 'r', encoding='utf-8') as f: whatsapp_text = f.read()

email_body_text = ""
if os.path.exists('email_shrnuti.txt'):
    with open('email_shrnuti.txt', 'r', encoding='utf-8') as f: email_body_text = f.read()

def download_map_file():
    if os.path.exists('mapa_zakazky.html'):
        files.download('mapa_zakazky.html')

output.register_callback('notebook.download_map', download_map_file)

# Přidání CC adresy do mailto URL
cc_email = "tausovahanka@seznam.cz"
mailto_url = f"mailto:pzvonicek@hvbreal.cz?cc={cc_email}&subject=Report zpracování inzerátů k datu: {datetime.now().strftime('%d.%m.%Y')}&body={urllib.parse.quote(email_body_text)}"

html_ui = f'''
<div style="padding: 20px; border: 1px solid #0078d4; border-radius: 10px; background-color: #f0f7ff; font-family: sans-serif;">
    <h4 style="margin-top:0; color: #0078d4;">✅ Mapa s aktivními odkazy připravena</h4>
    <div style="display: flex; gap: 10px; margin-top: 10px; flex-wrap: wrap;">
        <a href="{mailto_url}" style="display: inline-block; padding: 12px 20px; background-color: #0078d4; color: white; text-decoration: none; border-radius: 5px; font-weight: bold;">🚀 Odeslat report</a>
        <button onclick="copyWhatsApp()" style="padding: 12px 20px; background-color: #25D366; color: white; border: none; border-radius: 5px; font-weight: bold; cursor: pointer;">📱 Kopírovat WhatsApp</button>
        <button onclick="downloadMap()" style="padding: 12px 20px; background-color: #ff9800; color: white; border: none; border-radius: 5px; font-weight: bold; cursor: pointer;">🗺️ Stáhnout novou mapu</button>
    </div>
    <script>
    function copyWhatsApp() {{
        const text = `{whatsapp_text.replace('`', '\\`').replace('$', '\\$')}`;
        navigator.clipboard.writeText(text).then(() => alert('Zkopírováno!'));
    }}
    function downloadMap() {{
        google.colab.kernel.invokeFunction('notebook.download_map', [], {{}});
    }}
    </script>
</div>
'''
display(HTML(html_ui))

"""### **Interaktivní HTML Dashboard (Koncept)**
Tato buňka vytvoří prototyp sjednoceného výstupu, kde je mapa i interaktivní tabulka v jednom.
"""

import folium
import pandas as pd
import base64
import re
import os
import shutil
import pytz
import urllib.parse
import unicodedata
from IPython.display import HTML
from google.colab import userdata
from datetime import datetime

# --- 1. Generování Dashboardu ---
if 'final_vystup' in locals() and 'm' in locals():
    data_pro_html = []
    operator_assignments = {}

    seen_in_dashboard = set()
    unique_final_vystup = []
    for item in final_vystup:
        ad_fingerprint = hash(item['text'].strip())
        if ad_fingerprint not in seen_in_dashboard:
            seen_in_dashboard.add(ad_fingerprint)
            unique_final_vystup.append(item)

    operator_map = {}
    valid_passwords = ['1593', 'pavel']

    def remove_accents(input_str):
        nfkd_form = unicodedata.normalize('NFKD', input_str)
        return "".join([c for c in nfkd_form if not unicodedata.combining(c)])

    if 'df_m_full' in locals():
        for _, r in df_m_full.iterrows():
            if pd.notna(r.get('Jméno')) and pd.notna(r.get('Operátor')):
                op_name = str(r['Operátor']).strip()
                operator_map[str(r['Jméno']).strip()] = op_name
                pwd = remove_accents(op_name).lower()
                if pwd not in valid_passwords: valid_passwords.append(pwd)

    for item in unique_final_vystup:
        match = re.search(r'\|\s*([^|]*?)\s*\|', item['text'])
        agent_name = match.group(1).strip() if match else "-"
        op_name = operator_map.get(agent_name, "Neznámý")
        if op_name not in operator_assignments:
            operator_assignments[op_name] = []
        operator_assignments[op_name].append(item['text'])

    prague_tz = pytz.timezone('Europe/Prague')
    aktualizace_str = datetime.now(prague_tz).strftime('%d.%m.%Y %H:%M:%S')

    # Sběr dat pro tabulku a agregace vzdáleností dle krajů pro statistiku
    regional_assigned_distances = {}

    for idx, item in enumerate(unique_final_vystup, 1):
        lines = item['text'].split('\n')
        loc = lines[0]
        match = re.search(r'~(.*?) km \| (.*?) \|', item['text'])
        dist_val = float(match.group(1).strip()) if match else None
        dist_str = match.group(1).strip() if match else "-"
        agent_name = match.group(2).strip() if match else "-"
        operator_name = operator_map.get(agent_name, "-")
        clean_loc = re.sub(r'^[\d]+[\.\)]\s*', '', loc).strip()
        url = lines[-1]

        # Zjištění kraje z textu inzerátu pro statistiku
        norm_loc_for_stat = normalize_text(loc)
        target_kraj_norm = get_kraj_from_text(norm_loc_for_stat, obce_list)

        # Sjednocení klíče s ads_by_region
        if target_kraj_norm == "hlavni mesto praha":
            final_kraj_key = "Hlavní Město Praha"
        elif target_kraj_norm == "Neznamy":
            final_kraj_key = "Neznámý"
        else:
            clean_name = target_kraj_norm.replace(' kraj', '').strip().title()
            final_kraj_key = f"{clean_name} kraj"

        if dist_val is not None:
            if final_kraj_key not in regional_assigned_distances: regional_assigned_distances[final_kraj_key] = []
            regional_assigned_distances[final_kraj_key].append(dist_val)

        data_pro_html.append({
            '#': idx, 'Inzerát': loc, 'Vzdálenost (km)': dist_str,
            'Operátor': operator_name, 'Makléř': agent_name,
            'Kontakt': phone_map.get(clean_loc, ""),
            'Odkaz': f'<a href="{url}" target="_blank">Otevřít</a>'
        })

    all_regions = sorted(ads_by_region.keys())
    assigned_rows = []
    unassigned_rows = []

    for kr in all_regions:
        pocet_total = len(ads_by_region[kr])
        dists = regional_assigned_distances.get(kr, [])

        k_norm = normalize_text(kr).replace('kraj ', '').strip()
        vhodni_makleri = [m for m in makleri_db if k_norm in m['kraj_norm'] or (k_norm == 'hlavni mesto praha' and 'praha' in m['kraj_norm'])]
        pocet_makleru = len(vhodni_makleri)

        if pocet_makleru > 0:
            avg_dist = round(sum(dists) / len(dists), 1) if len(dists) > 0 else 0
            prumer_na_maklere = round(pocet_total / pocet_makleru, 1)
            assigned_rows.append(f"<tr><td>{kr}</td><td>{pocet_total}</td><td>{pocet_makleru}</td><td>{prumer_na_maklere}</td><td>{avg_dist}</td></tr>")
        else:
            unassigned_rows.append(f"<tr><td>{kr}</td><td>{pocet_total}</td><td>0</td><td>0</td><td>-</td></tr>")

    stats_title = f"📊 Statistika dle krajů (počet inzerátů ČR: {total_processed if 'total_processed' in locals() else 0}, z toho zpracovaných: {len(unique_final_vystup)})"
    stats_html = f"<div class='card'><h3>{stats_title}</h3><table><thead><tr><th>Kraj</th><th>Počet inzerátů</th><th>Počet makléřů</th><th>Průměr / Makléř</th><th>Průměrná vzdálenost (km)</th></tr></thead><tbody>"
    stats_html += "".join(assigned_rows) + "".join(unassigned_rows) + "</tbody></table></div>"

    operator_section_html = "<div class='card'><h3>📱 Sekce pro operátory</h3><div style='display:flex; flex-wrap:wrap; gap:15px;'>"
    for op, texts in sorted(operator_assignments.items()):
        combined_text = "\n\n".join([f"{i+1}. {t}" for i, t in enumerate(texts)])
        wa_url = f"https://wa.me/?text={urllib.parse.quote(combined_text)}"
        safe_op = op.replace(' ', '_')
        operator_section_html += f"""
        <div style='border:1px solid #ddd; padding:15px; border-radius:8px; background:#fafafa; flex:1; min-width:250px;'>
            <h4 style='margin-top:0;'>👤 {op}</h4>
            <p>Zakázek: {len(texts)}</p>
            <a href=\"{wa_url}\" target=\"_blank\" class=\"btn btn-wa\" style='display:block; margin-bottom:5px; text-align:center;'>WhatsApp</a>
            <button onclick=\"downloadOpText('{safe_op}')\" class=\"btn btn-copy\" style='display:block; width:100%;'>Stáhnout TXT</button>
            <textarea id=\"txt_{safe_op}\" style=\"display:none;\">{combined_text}</textarea>
        </div>"""
    operator_section_html += "</div></div>"

    map_html = m._repr_html_()
    table_html = pd.DataFrame(data_pro_html).to_html(escape=False, index=False, classes='pure-table')

    full_html = f"""<html><head><meta charset='utf-8'><style>
    body {{ font-family: 'Segoe UI', sans-serif; margin: 0; padding: 0; background: #f0f2f5; }}
    #lock-screen {{ position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: rgba(240, 242, 245, 0.8); z-index: 9999; display: flex; align-items: center; justify-content: center; backdrop-filter: blur(10px); }}
    .lock-box {{ background: white; padding: 30px; border-radius: 12px; box-shadow: 0 10px 25px rgba(0,0,0,0.1); text-align: center; }}
    #main-content {{ filter: blur(20px); transition: filter 0.5s ease; padding: 20px; }}
    .container {{ max-width: 1200px; margin: 0 auto; display: flex; flex-direction: column; gap: 25px; }}
    .card {{ background: white; padding: 20px; border-radius: 12px; box-shadow: 0 4px 6px rgba(0,0,0,0.05); margin-bottom: 20px; clear: both; }}
    .map-container {{ height: 600px; width: 100%; overflow: hidden; border-radius: 8px; }}
    table {{ width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 14px; }}
    th {{ background-color: #0078d4; color: white; padding: 12px; text-align: left; }}
    td {{ padding: 12px; border-bottom: 1px solid #eee; }}
    .btn {{ display: inline-block; padding: 10px 15px; border-radius: 6px; text-decoration: none; font-weight: bold; cursor: pointer; border: none; font-size: 14px; }}
    .btn-wa {{ background: #25D366; color: white; }}
    .btn-copy {{ background: #0078d4; color: white; }}
    input[type='password'] {{ padding: 10px; border: 1px solid #ddd; border-radius: 5px; margin-bottom: 10px; width: 200px; }}
    </style>
    <script>
    const allowed = {valid_passwords};
    function checkPassword() {{
        const val = document.getElementById('pass').value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, "");
        if (allowed.includes(val)) {{
            document.getElementById('lock-screen').style.display = 'none';
            document.getElementById('main-content').style.filter = 'none';
        }} else {{
            alert('Chybné heslo!');
        }}
    }}
    function downloadOpText(opId) {{
        const text = document.getElementById('txt_' + opId).value;
        const blob = new Blob([text], {{ type: 'text/plain;charset=utf-8' }});
        const link = document.createElement('a');
        link.href = URL.createObjectURL(blob);
        link.download = 'zakazky_' + opId + '.txt';
        link.click();
    }}
    </script>
    </head><body>
    <div id='lock-screen'>
        <div class='lock-box'>
            <h3>🔒 Přístup omezen</h3>
            <p>Zadejte jméno operátora nebo kód:</p>
            <input type='password' id='pass' onkeydown='if(event.key==="Enter") checkPassword()'><br>
            <button class='btn btn-copy' onclick='checkPassword()'>Vstoupit</button>
        </div>
    </div>
    <div id='main-content'>
        <div class='container'>
        <div style='text-align:center;'><h2>Přehled realitní inzerce</h2><p>Aktualizováno: {aktualizace_str}</p></div>
        {operator_section_html}
        <div class='card'><h3>📍 Mapa zakázek</h3><div class='map-container'>{map_html}</div></div>
        <div class='card' style='margin-top:30px;'>
            <h3>📋 Seznam unikátních inzerátů</h3>
            <p style='color:red; font-weight:bold; margin-top:-10px;'>- před voláním zkontrolujte, zda lokalita v inzerci souhlasí s regionem makléře, v případě neshody inzerci vyřaďte.</p>
            {table_html}
        </div>
        {stats_html}
        </div>
    </div>
    </body></html>"""

    filename = 'Dashboard.html'
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(full_html)
    print(f"✅ {filename} aktualizován s opravou průměrné vzdálenosti pro všechny kraje.")

    try:
        token = userdata.get('github_api') or userdata.get('GITHUB')
        if token:
            repo_name, repo_owner = "HVB", "DNA2026"
            repo_url = f"https://{token}@github.com/{repo_owner}/{repo_name}.git"
            os.system('git config --global user.email "automat@hvbreal.cz"')
            os.system('git config --global user.name "HVB Bot"')
            if os.path.exists(repo_name): shutil.rmtree(repo_name)
            if os.system(f'git clone {repo_url}') == 0:
                shutil.copy(filename, os.path.join(repo_name, filename))
                os.chdir(repo_name)
                os.system(f'git add {filename}')
                os.system(f'git commit -m "Fix regional average distance stats {aktualizace_str}"')
                os.system(f'git push {repo_url}')
                os.chdir('..')
                print("✅ Dashboard aktualizován na GitHubu.")
    except Exception as e: print(f"❌ Chyba GitHub: {e}")
