# -*- coding: utf-8 -*-
"""OCTO_komplet_3.10 alfa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f9YVFuItJtrQkultdDFaeJAWtP6llAuu
"""

# -*- coding: utf-8 -*-

"""OCTO_komplet_3_10_AUT_ORS_OSRM alfa.ipynb

**Automatické načtení souborů z Disku Google OCTO komplet AUT ORS OSRM Email**
"""

from google.colab import drive
import os
import shutil

# Mount Google Drive
drive.mount('/content/drive')

# Define source and destination
source_folder = '/content/drive/MyDrive/HVB'
files_to_copy = ['obce01.csv', 'Makléři.xlsx', 'Export výstup.txt']

print("Copying files from Drive...")
for f in files_to_copy:
    src = os.path.join(source_folder, f)
    if os.path.exists(src):
        shutil.copy(src, '/content/')
        print(f"✅ {f} copied.")
    else:
        print(f"❌ {f} not found in {source_folder}")

"""**Export**"""

import pandas as pd
import re
import unicodedata
import os

def normalize_text(text):
    if pd.isna(text): return ""
    text = str(text).strip().lower()
    # Sjednocení oddělovačů (čárky/pomlčky) na mezery pro lepší vyhledávání
    text = text.replace('-', ' ').replace(',', ' ')
    text = unicodedata.normalize('NFKD', text).encode('ascii', 'ignore').decode('utf-8')
    text = text.replace('moravskoslezky', 'moravskoslezsky')
    return " ".join(text.split())

def get_kraj_from_text(norm_loc, obce_list):
    unique_kraje = set(o['kraj'] for o in obce_list)
    for k in unique_kraje:
        if re.search(r'\b' + re.escape(k) + r'\b', norm_loc.replace('kraj', '')):
            return k
    if "praha" in norm_loc and "okres praha" not in norm_loc: return "hlavni mesto praha"
    if "hlavni mesto praha" in norm_loc: return "hlavni mesto praha"
    unique_okresy = {o['okres']: o['kraj'] for o in obce_list}
    for okr, kr in unique_okresy.items():
        if re.search(r'\b' + re.escape(okr) + r'\b', norm_loc.replace('okres', '')): return kr
    for o in sorted(obce_list, key=lambda x: len(x['obec']), reverse=True):
        if re.search(r'\b' + re.escape(o['obec']) + r'\b', norm_loc): return o['kraj']
    return "Neznamy"

# Načtení základních dat
if os.path.exists('/content/obce01.csv'):
    df_obce = pd.read_csv('/content/obce01.csv', sep=';', encoding='utf-8')
    obce_list = [{'obec': normalize_text(r['Obec']), 'okres': normalize_text(r.get('Okres', '')), 'kraj': normalize_text(r.get('Kraj', ''))} for _, r in df_obce.iterrows()]

blocks = [] # Initialize blocks to an empty list
if os.path.exists('/content/Makléři.xlsx'):
    df_m_full = pd.read_excel('/content/Makléři.xlsx')
    makleri_info = []
    for _, r in df_m_full.iterrows():
        if pd.isna(r['Jméno']): continue
        makleri_info.append({'jmeno': str(r['Jméno']).strip(), 'kraj_norm': normalize_text(r.get('Kraj', ''))})

if os.path.exists('/content/Export výstup.txt'):
    with open('/content/Export výstup.txt', 'r', encoding='utf-8') as f:
        raw_content = f.read()
        blocks = [b.strip() for b in re.split(r'\n(?=\d+\.)', '\n' + raw_content) if b.strip()]
        if len(blocks) <= 1:
            blocks = [b.strip() for b in raw_content.split('\n\n') if b.strip()]

def find_best_coords(norm_loc, df_obce_sorted):
    target_kraj = get_kraj_from_text(norm_loc, obce_list)
    potential_matches = []
    for _, row in df_obce_sorted.iterrows():
        norm_obec = normalize_text(row['Obec'])
        # Robustnější hledání podřetězce
        if norm_obec in norm_loc:
            score = 0
            if normalize_text(row['Kraj']) == target_kraj: score += 10
            if normalize_text(row.get('Okres', '')) in norm_loc: score += 5
            potential_matches.append((score, [float(row['Longitude']), float(row['Latitude'])]))
    if potential_matches:
        return sorted(potential_matches, key=lambda x: x[0], reverse=True)[0][1]
    return None

print(f"Načteno {len(blocks)} inzerátů.")

"""**KRAJE**"""

ads_by_region = {}

for block in blocks:
    lines = block.split('\n')
    if lines:
        full_loc = re.sub(r'^[\d]+[\.\)]\s*', '', lines[0])
        norm_loc = normalize_text(full_loc)
        target_kraj_norm = get_kraj_from_text(norm_loc, obce_list)

        # Oprava: Odstranění duplicitního 'kraj' v názvu
        if target_kraj_norm == "hlavni mesto praha":
            final_kraj = "Hlavní Město Praha"
        elif target_kraj_norm == "Neznamy":
            final_kraj = "Neznámý"
        else:
            clean_name = target_kraj_norm.replace(' kraj', '').strip().title()
            final_kraj = f"{clean_name} kraj"

        if final_kraj not in ads_by_region:
            ads_by_region[final_kraj] = []
        ads_by_region[final_kraj].append(full_loc)

print("=== JMENOVITÝ SEZNAM INZERÁTŮ DLE KRAJŮ ===\n")
for kraj in sorted(ads_by_region.keys()):
    print(f"📍 {kraj}:")
    for i, ad in enumerate(sorted(ads_by_region[kraj]), 1):
        print(f"  {i}. {ad}")
    print("-" * 30)

"""### **Hlavní výpočet a Export (ORS)**
*Tato sekce obsahuje finální sjednocenou logiku pro výpočet silničních vzdáleností a uložení souboru `ORS_komplet.txt`.*
"""

import pandas as pd
import requests
import time
import re
import unicodedata
import os
from google.colab import userdata, files
from IPython.display import display, HTML, clear_output

ORS_API_KEY = userdata.get('ORS_API_KEY')
ORS_DELAY = 1.6

def normalize_text(text):
    if pd.isna(text): return ""
    text = str(text).strip().lower()
    text = text.replace('-', ' ').replace(',', ' ')
    text = unicodedata.normalize('NFKD', text).encode('ascii', 'ignore').decode('utf-8')
    text = text.replace('moravskoslezky', 'moravskoslezsky')
    return " ".join(text.split())

def get_kraj_from_text(norm_loc, obce_list):
    unique_kraje = set(o['kraj'] for o in obce_list)
    for k in unique_kraje:
        if re.search(r'\b' + re.escape(k) + r'\b', norm_loc.replace('kraj', '')):
            return k
    if "praha" in norm_loc and "okres praha" not in norm_loc: return "hlavni mesto praha"
    if "hlavni mesto praha" in norm_loc: return "hlavni mesto praha"
    unique_okresy = {o['okres']: o['kraj'] for o in obce_list}
    for okr, kr in unique_okresy.items():
        if re.search(r'\b' + re.escape(okr) + r'\b', norm_loc.replace('okres', '')): return kr
    for o in sorted(obce_list, key=lambda x: len(x['obec']), reverse=True):
        if re.search(r'\b' + re.escape(o['obec']) + r'\b', norm_loc): return o['kraj']
    return "Neznamy"

def find_best_coords(norm_loc, df_obce_sorted):
    target_kraj = get_kraj_from_text(norm_loc, obce_list)
    potential_matches = []

    for _, row in df_obce_sorted.iterrows():
        norm_obec = normalize_text(row['Obec'])
        # Hledáme přesnou shodu slova v textu
        if re.search(r'\b' + re.escape(norm_obec) + r'\b', norm_loc):
            score = 0
            row_kraj = normalize_text(row.get('Kraj', ''))
            row_okres = normalize_text(row.get('Okres', ''))

            # Zásadní priorita: Shoda kraje
            if row_kraj == target_kraj:
                score += 50
            elif target_kraj != "Neznamy":
                score -= 100 # Tvrdá penalizace za špatný kraj

            # Bonus za shodu okresu v textu
            if row_okres and row_okres in norm_loc:
                score += 30

            # Bonus za délku názvu obce (řeší Benešov vs Benešov nad Černou)
            score += len(norm_obec)

            potential_matches.append((score, [float(row['Longitude']), float(row['Latitude'])]))

    if potential_matches:
        # Vrátíme výsledek s nejvyšším skóre
        return sorted(potential_matches, key=lambda x: x[0], reverse=True)[0][1]
    return None

if 'df_obce' not in locals():
    df_obce = pd.read_csv('/content/obce01.csv', sep=';', encoding='utf-8')
obce_list = [{'obec': normalize_text(r['Obec']), 'okres': normalize_text(r.get('Okres', '')), 'kraj': normalize_text(r.get('Kraj', ''))} for _, r in df_obce.iterrows()]

if 'df_m_full' not in locals():
    df_m_full = pd.read_excel('/content/Makléři.xlsx')

if 'blocks' not in locals():
    with open('/content/Export výstup.txt', 'r', encoding='utf-8') as f:
        raw_content = f.read()
        blocks = [b.strip() for b in re.split(r'\n(?=\d+\.)', '\n' + raw_content) if b.strip()]
        if len(blocks) <= 1: blocks = [b.strip() for b in raw_content.split('\n\n') if b.strip()]

df_obce_sorted = df_obce.sort_values(by='Obec', key=lambda x: x.str.len(), ascending=False).copy()
makleri_db = []
for _, r in df_m_full.iterrows():
    if pd.isna(r['Jméno']): continue
    coords = None
    if pd.notna(r.get('Souřadnice')):
        try:
            c = str(r['Souřadnice']).replace(' ', '').split(',')
            if len(c) == 2:
                val1, val2 = float(c[0]), float(c[1])
                coords = [val2, val1] if 48 < val1 < 52 else [val1, val2]
        except: pass
    makleri_db.append({
        'jmeno': str(r['Jméno']).strip(),
        'kraj_norm': normalize_text(r.get('Kraj', '')),
        'pos': coords,
        'limit': float(r.get('Maximální vzdálenost od adresy (km)', 50)),
        'kapacita': int(r.get('Maximální počet výstupů', 10)) if pd.notna(r.get('Maximální počet výstupů')) else 10,
        'Byty': str(r.get('Byty', '')).lower() in ['ano', 'x', '1', 'true'],
        'Domy': str(r.get('Domy', '')).lower() in ['ano', 'x', '1', 'true'],
        'kontakt': str(r.get('Telefon', ''))
    })

final_results = []
distance_cache = {}
start_time = time.time()

for idx, block in enumerate(blocks, 1):
    elapsed = time.time() - start_time
    clear_output(wait=True)
    display(HTML(f'''<div style="padding:10px; border:1px solid #ddd; border-radius:5px; background:#f9f9f9;"><b>⏳ Probíhá výpočet: {idx} / {len(blocks)}</b><br>⏱ Čas: {int(elapsed // 60):02d}:{int(elapsed % 60):02d}</div>'''))
    lines = block.split('\n')
    if not lines: continue
    loc = re.sub(r"^[\d]+[\.\)]\s*", '', lines[0])
    norm_loc = normalize_text(loc)
    target_kraj = get_kraj_from_text(norm_loc, obce_list)
    found_coords = find_best_coords(norm_loc, df_obce_sorted)
    row = {'Inzerát': loc, 'Kraj': target_kraj}
    kraj_agents = [m for m in makleri_db if target_kraj in m['kraj_norm'] or (target_kraj == 'hlavni mesto praha' and 'praha' in m['kraj_norm'])]
    if found_coords and kraj_agents:
        for agent in kraj_agents:
            if not agent['pos']: continue
            cache_key = (tuple(found_coords), tuple(agent['pos']))
            if cache_key in distance_cache:
                row[f"{agent['jmeno']} (km)"] = distance_cache[cache_key]
            else:
                try:
                    try:
                        res = requests.post('https://api.openrouteservice.org/v2/directions/driving-car',
                                           json={"coordinates": [found_coords, agent['pos']]},
                                           headers={'Authorization': ORS_API_KEY, 'Content-Type': 'application/json'},
                                           timeout=10)
                        if res.status_code == 200:
                            dist_km = round(res.json()['routes'][0]['segments'][0]['distance'] / 1000.0, 1)
                            distance_cache[cache_key] = dist_km
                            row[f"{agent['jmeno']} (km)"] = dist_km
                            time.sleep(ORS_DELAY)
                        else:
                            raise ValueError(f"ORS chyba: {res.status_code}")
                    except Exception as e:
                        try:
                            url = f"http://router.project-osrm.org/route/v1/driving/{found_coords[0]},{found_coords[1]};{agent['pos'][0]},{agent['pos'][1]}?overview=false"
                            res_osrm = requests.get(url, timeout=5)
                            if res_osrm.status_code == 200:
                                data = res_osrm.json()
                                if "routes" in data and len(data["routes"]) > 0:
                                    dist_km = round(data["routes"][0]["distance"] / 1000.0, 1)
                                    distance_cache[cache_key] = dist_km
                                    row[f"{agent['jmeno']} (km)"] = dist_km
                                else: row[f"{agent['jmeno']} (km)"] = "N/A"
                            else: row[f"{agent['jmeno']} (km)"] = "N/A"
                        except: row[f"{agent['jmeno']} (km)"] = "N/A"
                        time.sleep(0.1)
                except: row[f"{agent['jmeno']} (km)"] = "N/A"
    final_results.append(row)

df_export = pd.DataFrame(final_results)
df_export.insert(0, 'ID', range(1, len(df_export) + 1))
df_export.to_csv('ORS_komplet.txt', sep='\t', index=False, encoding='utf-8')
display(df_export.fillna('-'))

"""**Validace limitů a výstup pro navolávačku**"""

def detect_type(text_blob):
    text = normalize_text(text_blob)
    house_keywords = ['rodinny dum', 'rd', 'chata', 'chalupa', 'vila', 'prodej domu', 'rodinneho domu']
    if any(x in text for x in house_keywords):
        return 'Domy'
    if any(x in text for x in ['pozemek', 'zahrada', 'parcela']):
        return 'Pozemky'
    if any(x in text for x in ['komerc', 'kancelar', 'sklad', 'prostor', 'objekt']):
        return 'Komerční'
    return 'Byty'

# Mapování URL a telefonů
url_map = {}
phone_map = {}
for block in blocks:
    lines = block.split('\n')
    if len(lines) > 0:
        loc_key = re.sub(r'^[\d]+[\.\)]\s*', '', lines[0]).strip()
        urls = re.findall(r'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+', block)
        if urls: url_map[loc_key] = urls[0]
        phone_match = re.search(r'(?:Tel|Tel\.|Telefon):?\s*(\+?\d[\d\s]{8,})', block, re.IGNORECASE)
        if phone_match: phone_map[loc_key] = phone_match.group(1).strip()

# Mapování makléř -> operátor
agent_to_operator = {}
if 'df_m_full' in locals():
    for _, r in df_m_full.iterrows():
        if pd.notna(r.get('Jméno')) and pd.notna(r.get('Operátor')):
            agent_to_operator[str(r['Jméno']).strip()] = str(r['Operátor']).strip()

# Resetování makléřů
for m in makleri_db:
    m['aktualne_prirazeno'] = 0
    m['base_capacity'] = int(m.get('kapacita', 10)) if m.get('kapacita', 10) > 0 else 0

op_counts = {op: 0 for op in set(agent_to_operator.values())}
final_vystup_raw = []
filtered_out_info = []

if os.path.exists('ORS_komplet.txt'):
    df_in = pd.read_csv('ORS_komplet.txt', sep='\t')
    seen_urls = set()
    unique_rows = []
    for _, row in df_in.iterrows():
        txt = str(row['Inzerát']).strip()
        key = re.sub(r'^[\d]+[\.\)]\s*', '', txt).strip()
        url = url_map.get(key)
        if url:
            if url not in seen_urls:
                seen_urls.add(url)
                unique_rows.append(row)
            else:
                filtered_out_info.append({'ID': row.get('ID', 'N/A'), 'Inzerát': txt, 'Důvod': 'Duplicita URL'})
        else:
            filtered_out_info.append({'ID': row.get('ID', 'N/A'), 'Inzerát': txt, 'Důvod': 'Chybí URL'})

    # 1. KROK: Prvotní přiřazení (operátorka s nejméně zakázkami + nejbližší makléř)
    for r in unique_rows:
        kraj_norm = str(r['Kraj'])
        vhodni = []
        for a in makleri_db:
            if (kraj_norm in a['kraj_norm'] or (kraj_norm == 'hlavni mesto praha' and 'praha' in a['kraj_norm'])) and a['base_capacity'] > 0:
                dist = r.get(f"{a['jmeno']} (km)")
                if pd.notna(dist) and dist != 'N/A' and float(dist) <= a['limit']:
                    op_name = agent_to_operator.get(a['jmeno'], "Neznámý")
                    vhodni.append({'agent': a, 'dist': float(dist), 'op': op_name})

        if vhodni:
            # Priorita 1: Operátor s aktuálně nejnižším počtem zakázek
            # Priorita 2: Vzdálenost k makléři
            vhodni.sort(key=lambda x: (op_counts.get(x['op'], 0), x['dist']))
            target = None
            for v in vhodni:
                if v['agent']['aktualne_prirazeno'] < v['agent']['base_capacity']:
                    target = v
                    break
            if not target: target = vhodni[0]

            target['agent']['aktualne_prirazeno'] += 1
            op_counts[target['op']] = op_counts.get(target['op'], 0) + 1
            final_vystup_raw.append({'row': r, 'agent': target['agent'], 'dist': target['dist'], 'op': target['op']})
        else:
            filtered_out_info.append({'ID': r.get('ID', 'N/A'), 'Inzerát': r['Inzerát'], 'Důvod': 'Mimo dosah'})

    # 2. KROK: Korekční rebalance (pokud je rozdíl mezi operátorkami > 1)
    all_ops = list(op_counts.keys())
    if len(all_ops) > 1:
        max_iter = 200 # Dostatečná rezerva pro vyrovnání
        while max_iter > 0:
            max_iter -= 1
            min_op = min(op_counts, key=op_counts.get)
            max_op = max(op_counts, key=op_counts.get)

            if op_counts[max_op] - op_counts[min_op] <= 1:
                break

            moved = False
            candidates = []
            # Hledáme inzerát u max_op, který lze přesunout k min_op
            for item in final_vystup_raw:
                if item['op'] == max_op:
                    r = item['row']
                    kraj_norm = str(r['Kraj'])
                    for a in makleri_db:
                        if agent_to_operator.get(a['jmeno']) == min_op:
                            if (kraj_norm in a['kraj_norm'] or (kraj_norm == 'hlavni mesto praha' and 'praha' in a['kraj_norm'])):
                                d_new = r.get(f"{a['jmeno']} (km)")
                                if pd.notna(d_new) and d_new != 'N/A' and float(d_new) <= a['limit']:
                                    if a['aktualne_prirazeno'] < a['base_capacity']:
                                        # Penalizace = nárůst vzdálenosti při přesunu
                                        penalty = float(d_new) - item['dist']
                                        candidates.append({'item': item, 'new_agent': a, 'new_dist': float(d_new), 'penalty': penalty})

            if candidates:
                # Vybereme přesun s NEJMENŠÍM rozdílem ve vzdálenosti (penalty)
                best = min(candidates, key=lambda x: x['penalty'])

                # Provedení přesunu v datech
                best['item']['agent']['aktualne_prirazeno'] -= 1
                best['item']['agent'] = best['new_agent']
                best['item']['dist'] = best['new_dist']
                best['item']['op'] = min_op
                best['new_agent']['aktualne_prirazeno'] += 1

                op_counts[max_op] -= 1
                op_counts[min_op] += 1
                moved = True

            if not moved: break

    # Formátování výstupu pro WhatsApp
    final_vystup = []
    for item in final_vystup_raw:
        r = item['row']
        a = item['agent']
        txt = str(r['Inzerát']).strip()
        key = re.sub(r'^[\d]+[\.\)]\s*', '', txt).strip()
        actual_phone = phone_map.get(key, "")
        phone_line = f"\nTel: {actual_phone}" if actual_phone else ""
        ad_url = url_map.get(key, "")
        block_txt = f"{txt}{phone_line}\n~{item['dist']} km | {a['jmeno']} | {a['kontakt']}\n{ad_url}"
        final_vystup.append({'dist': item['dist'], 'text': block_txt})

    final_vystup.sort(key=lambda x: x['dist'])
    with open('whatsapp_vystup_finalni.txt', 'w', encoding='utf-8') as f:
        for i, item in enumerate(final_vystup, 1): f.write(f"{i}. {item['text']}\n\n")

    print(f"✅ Zpracováno s korekční rebalancí (rozdíl <= 1). Celkem {len(final_vystup)} unikátních inzerátů.")

import pandas as pd
from IPython.display import HTML
import re

# 1. Identifikace duplicit striktně podle URL
url_to_blocks = {}

for block in blocks:
    urls = re.findall(r'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+', block)
    if urls:
        url = urls[0]
        if url not in url_to_blocks:
            url_to_blocks[url] = []
        url_to_blocks[url].append(block)

duplicitni_data = []
for url, found_blocks in url_to_blocks.items():
    if len(found_blocks) > 1:
        for b in found_blocks:
            lines = b.split('\n')
            loc = lines[0].strip() if lines else "Neznámý inzerát"
            duplicitni_data.append({
                'Shodná URL': f'<a href="{url}" target="_blank">{url}</a>',
                'Název / Lokace': loc,
                'Celkem nalezeno kopií': len(found_blocks)
            })

# 2. Vytvoření souboru Duplicity.html
if duplicitni_data:
    df_duplicity = pd.DataFrame(duplicitni_data)
    html_table = df_duplicity.to_html(escape=False, index=False)

    html_content = f"""<html><head><meta charset='utf-8'><style>
    body {{ font-family: sans-serif; padding: 20px; }}
    table {{ border-collapse: collapse; width: 100%; margin-top: 10px; }}
    th {{ background: #d32f2f; color: white; padding: 12px; text-align: left; }}
    td {{ border: 1px solid #ddd; padding: 10px; }}
    tr:nth-child(even) {{ background: #fef2f2; }}
    </style></head><body>
    <h2>⚠️ Seznam nalezených duplicit (shodné URL)</h2>
    <p>Následující inzeráty byly identifikovány jako duplicitní, protože odkazují na stejnou webovou adresu.</p>
    {html_table}
    </body></html>"""

    with open('Duplicity.html', 'w', encoding='utf-8') as f:
        f.write(html_content)
    print(f"✅ Soubor Duplicity.html byl vytvořen (nalezeno {len(url_to_blocks)} unikátních URL s duplicitami).")
else:
    print("ℹ️ Žádné duplicity podle URL nebyly nalezeny.")

display(HTML(html_table) if duplicitni_data else "Žádné duplicity")

"""### **Celkové shrnutí a statistiky**
Vytížení makléřů a distribuci inzerátů.
"""

import pandas as pd
import re
import numpy as np
import os

FINAL_VALIDATED_FILE = 'whatsapp_vystup_finalni.txt'

# 1. Analýza přiřazení
assigned_counts = {}
if 'final_vystup' in locals():
    for item in final_vystup:
        match = re.search(r'\|\s*([^|]+?)\s*\|', item['text'])
        if match:
            name = match.group(1).strip()
            assigned_counts[name] = assigned_counts.get(name, 0) + 1

# 2. Vytížení makléřů
summary_agents = []
for m in makleri_db:
    name = m['jmeno']
    if not name or name == "nan" or name == "": continue
    safe_count = assigned_counts.get(name, 0)
    safe_limit = m['kapacita'] if m['kapacita'] > 0 else 10
    utilization = (safe_count / safe_limit * 100)
    summary_agents.append(f"{name} | {safe_count} | {safe_limit} | {utilization:.1f}%")

# 3. Statistiky
geo_stats = {}
d_bins = {'0-15': 0, '15-30': 0, '30-50': 0, '50+': 0}

if 'final_vystup' in locals():
    for item in final_vystup:
        lines = item['text'].split('\n')
        loc_parts = lines[0].split(',')
        kraj_key = loc_parts[-1].strip() if loc_parts else "Neznámý"
        geo_stats[kraj_key] = geo_stats.get(kraj_key, 0) + 1

        d = item['dist']
        if d <= 15: d_bins['0-15'] += 1
        elif d <= 30: d_bins['15-30'] += 1
        elif d <= 50: d_bins['30-50'] += 1
        else: d_bins['50+'] += 1

total_processed = len(blocks) if 'blocks' in locals() else 0
total_exported = len(final_vystup) if 'final_vystup' in locals() else 0

print("=== Shrnutí : Vytížení makléřů ===")
print("Jméno | Přiřazeno | Limit | Využití %")
for line in summary_agents: print(line)

print("\n=== Inzeráty dle krajů ===")
for kraj_item, count_item in sorted(geo_stats.items(), key=lambda x: x[1], reverse=True):
    print(f"{kraj_item} | {count_item}")

print(f"\n=== Rozdělení dle vzdálenosti ===")
print(f"0-15 km: {d_bins['0-15']} | 15-30 km: {d_bins['15-30']} | 30-50 km: {d_bins['30-50']} | 50+ km: {d_bins['50+']}")

"""**Emailové shrnutí**"""

from datetime import datetime
import os

actual_total = total_processed if 'total_processed' in locals() else 0
actual_exported = total_exported if 'total_exported' in locals() else 0
actual_filtered = max(0, actual_total - actual_exported)

# Definice textu emailu
email_body = f"""Dobrý den,\n\nposílám shrnutí dnešního zpracování inzerátů ze dne {datetime.now().strftime('%d.%m.%Y')}.\n\nStatistiky:\n- Celkem nalezeno: {actual_total}\n- Úspěšně exportováno: {actual_exported}\n- Odfiltrováno (mimo dosah/duplicity): {actual_filtered}\n\nDetailní report a interaktivní mapa jsou k dispozici v příloze nebo na níže uvedeném odkazu:\nhttps://dna2026.github.io/HVB/Dashboard.html\n\nS pozdravem,\nAutomatizovaný systém"""

"""Finální report a statistiky z dnešního zpracování realitních inzerátů.

Vzhledem k postupující automatizaci bude od zítřejšího dne finalizace reportu k dispozici pouze na níže uvedeném
webu s možností variantního zpracování:

1. zpracování na PC - přehlednější a intuitivnější (níže uvedený web si uložte pro každodenní zpracování)
2. zpracování na mobilním telefonu (stávající verze) - sdílejte (nebo kopírujte) data do Whatsapp
z webového rozhraní (pošlete sama sobě) a postupujte dle zvyklostí

Detailní rozbor (s možností sdílení WhatsApp a datem aktualizace) je k dispozici zde:
https://dna2026.github.io/HVB/Dashboard.html

S pozdravem,
Automatizovaný systém zpracování dat
"""

with open('email_shrnuti.txt', 'w', encoding='utf-8') as f_out:
    f_out.write(email_body)

print("=== NÁHLED EMAILU S AKTIVNÍM ODKAZEM ===")
print(email_body)

"""### HTML Report s Mapou"""

import folium
import pandas as pd
import re
import os
import random
from collections import Counter

output_filename = 'mapa_zakazky.html'

# Použijeme standardní OpenStreetMap s vynuceným HTTPS a detekcí retina displejů pro lepší stabilitu
tile_url = "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
tile_attr = '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'

m = folium.Map(
    location=[49.8, 15.5],
    zoom_start=8,
    tiles=tile_url,
    attr=tile_attr,
    detect_retina=True
)

assigned_map = {}
if 'final_vystup' in locals():
    for item in final_vystup:
        lines = item['text'].strip().split('\n')
        if not lines: continue
        raw_line = lines[0].strip()
        clean_key = re.sub(r'^[\d]+[\.\)]\s*', '', raw_line)
        match_agent = re.search(r'\|\s*([^|]*?)\s*\|', item['text'])
        if match_agent:
            assigned_map[clean_key] = match_agent.group(1).strip()
        else:
            assigned_map[clean_key] = "Ano"

if 'makleri_db' in locals():
    for agent in sorted(makleri_db, key=lambda x: x['limit'] if pd.notna(x['limit']) else 0, reverse=True):
        if agent['jmeno'] and agent['pos']:
            folium.Marker(
                location=[agent['pos'][1], agent['pos'][0]],
                popup=f"<b>Makléř:</b> {agent['jmeno']}",
                icon=folium.Icon(color='purple', icon='user'),
                tooltip=f"Makléř: {agent['jmeno']} | Limit: {agent['limit']} km"
            ).add_to(m)

            folium.Circle(
                location=[agent['pos'][1], agent['pos'][0]],
                radius=agent['limit'] * 1000,
                color='green', weight=2, fill=True, fill_opacity=0.06,
                tooltip=f"Oblast působnosti: {agent['jmeno']} ({agent['limit']} km)"
            ).add_to(m)

if 'df_export' in locals():
    # Nejprve spočítáme výskyty na stejných souřadnicích pro tooltip
    loc_coords = []
    for _, row in df_export.iterrows():
        c = find_best_coords(normalize_text(str(row['Inzerát'])), df_obce_sorted)
        if c: loc_coords.append(tuple(c))

    counts = Counter(loc_coords)

    for _, row in df_export.iterrows():
        inzerat_text = str(row['Inzerát']).strip()
        clean_inzerat = re.sub(r'^[\d]+[\.\)]\s*', '', inzerat_text)
        orig_coords = find_best_coords(normalize_text(inzerat_text), df_obce_sorted)

        if orig_coords:
            count_here = counts[tuple(orig_coords)]
            # Aplikujeme jitter pro vizuální rozlišení
            jitter_lat = orig_coords[1] + random.uniform(-0.003, 0.003)
            jitter_lon = orig_coords[0] + random.uniform(-0.003, 0.003)

            agent_name = assigned_map.get(clean_inzerat) or assigned_map.get(inzerat_text)
            is_assigned = agent_name is not None
            dot_color = 'green' if is_assigned else 'red'
            status = f"Přiřazeno: {agent_name}" if is_assigned else "Odfiltrováno"
            ad_url = url_map.get(inzerat_text, url_map.get(clean_inzerat, ""))
            link_html = f'<a href="{ad_url}" target="_blank">Odkaz</a>' if ad_url else "-"

            # Tooltip s informací o počtu odkazů v místě
            t_text = f"{inzerat_text}"
            if count_here > 1:
                t_text += f" (V této lokalitě je celkem {count_here} inzerátů)"

            folium.CircleMarker(
                location=[jitter_lat, jitter_lon],
                radius=6,
                popup=folium.Popup(f"<b>{inzerat_text}</b><br>Stav: {status}<br>{link_html}", max_width=350),
                tooltip=t_text,
                color=dot_color,
                fill=True,
                fill_opacity=0.8
            ).add_to(m)

m.save(output_filename)
print(f"✅ Mapa {output_filename} uložena s tooltipy pro počet inzerátů v místě.")

import zipfile
from google.colab import files
import os

# Aktualizace ZIP archivu s opravenou mapou (aktivní odkazy)
files_to_zip = ['whatsapp_vystup_finalni.txt', 'mapa_zakazky.html', 'ORS_komplet.txt', 'email_shrnuti.txt']
zip_filename = 'vystup_komplet_final_v3.zip'

with zipfile.ZipFile(zip_filename, 'w') as zipf:
    for f in files_to_zip:
        if os.path.exists(f):
            zipf.write(f)

print(f"✅ Archiv aktualizován: {zip_filename}")

"""### **Finální stažení a odeslání**
Tato buňka zajistí stažení všech vytvořených souborů a zobrazí tlačítko pro Thunderbird.
"""

import os
import urllib.parse
from google.colab import files
from IPython.display import display, HTML
from google.colab import output
from datetime import datetime

# Refresh UI data
whatsapp_text = ""
if os.path.exists('whatsapp_vystup_finalni.txt'):
    with open('whatsapp_vystup_finalni.txt', 'r', encoding='utf-8') as f: whatsapp_text = f.read()

email_body_text = ""
if os.path.exists('email_shrnuti.txt'):
    with open('email_shrnuti.txt', 'r', encoding='utf-8') as f: email_body_text = f.read()

def download_map_file():
    if os.path.exists('mapa_zakazky.html'):
        files.download('mapa_zakazky.html')

output.register_callback('notebook.download_map', download_map_file)

# Přidání CC adresy do mailto URL
cc_email = "tausovahanka@seznam.cz"
mailto_url = f"mailto:pzvonicek@hvbreal.cz?cc={cc_email}&subject=Report zpracování inzerátů k datu: {datetime.now().strftime('%d.%m.%Y')}&body={urllib.parse.quote(email_body_text)}"

html_ui = f'''
<div style="padding: 20px; border: 1px solid #0078d4; border-radius: 10px; background-color: #f0f7ff; font-family: sans-serif;">
    <h4 style="margin-top:0; color: #0078d4;">✅ Mapa s aktivními odkazy připravena</h4>
    <div style="display: flex; gap: 10px; margin-top: 10px; flex-wrap: wrap;">
        <a href="{mailto_url}" style="display: inline-block; padding: 12px 20px; background-color: #0078d4; color: white; text-decoration: none; border-radius: 5px; font-weight: bold;">🚀 Odeslat report</a>
        <button onclick="copyWhatsApp()" style="padding: 12px 20px; background-color: #25D366; color: white; border: none; border-radius: 5px; font-weight: bold; cursor: pointer;">📱 Kopírovat WhatsApp</button>
        <button onclick="downloadMap()" style="padding: 12px 20px; background-color: #ff9800; color: white; border: none; border-radius: 5px; font-weight: bold; cursor: pointer;">🗺️ Stáhnout novou mapu</button>
    </div>
    <script>
    function copyWhatsApp() {{
        const text = `{whatsapp_text.replace('`', '\\`').replace('$', '\\$')}`;
        navigator.clipboard.writeText(text).then(() => alert('Zkopírováno!'));
    }}
    function downloadMap() {{
        google.colab.kernel.invokeFunction('notebook.download_map', [], {{}});
    }}
    </script>
</div>
'''
display(HTML(html_ui))

"""### **Interaktivní HTML Dashboard (Koncept)**
Tato buňka vytvoří prototyp sjednoceného výstupu, kde je mapa i interaktivní tabulka v jednom.
"""

import folium
import pandas as pd
import base64
import re
import os
import shutil
import pytz
import urllib.parse
import unicodedata
from IPython.display import HTML
from google.colab import userdata
from datetime import datetime

# --- 1. Sjednocená příprava Dashboardu ---
if 'final_vystup' in locals() and 'm' in locals():
    # Příprava mapy
    folium.TileLayer(
        tiles='https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
        attr='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
        name='OpenStreetMap', overlay=False, control=False
    ).add_to(m)

    # Příprava dat pro tabulku a sekce
    seen_in_dashboard = set()
    unique_final_vystup = []
    for item in final_vystup:
        lines = item['text'].split('\n')
        raw_ad_text = lines[0].strip()
        ad_fingerprint = re.sub(r'^[\d]+[\.\)]\s*', '', raw_ad_text).strip()
        if ad_fingerprint not in seen_in_dashboard:
            seen_in_dashboard.add(ad_fingerprint)
            unique_final_vystup.append(item)

    operator_map = {}
    valid_passwords = ['1593', 'pavel']
    def remove_accents(input_str):
        nfkd_form = unicodedata.normalize('NFKD', input_str)
        return "".join([c for c in nfkd_form if not unicodedata.combining(c)])

    if 'df_m_full' in locals():
        for _, r in df_m_full.iterrows():
            if pd.notna(r.get('Jméno')) and pd.notna(r.get('Operátor')):
                op_name = str(r['Operátor']).strip()
                operator_map[str(r['Jméno']).strip()] = op_name
                pwd = remove_accents(op_name).lower()
                if pwd not in valid_passwords: valid_passwords.append(pwd)

    data_pro_html = []
    operator_assignments = {}
    regional_stats = {}

    for idx, item in enumerate(unique_final_vystup, 1):
        lines = item['text'].split('\n')
        loc = lines[0].strip()
        match_agent = re.search(r'\|\s*([^|]+?)\s*\|', item['text'])
        agent_name = match_agent.group(1).strip() if match_agent else "-"
        dist_val = item['dist']
        op_name = operator_map.get(agent_name, "-")

        clean_loc = re.sub(r'^[\d]+[\.\)]\s*', '', loc).strip()
        ad_url = url_map.get(clean_loc, "")

        # Výpočet regionu pro statistiku
        target_kraj_norm = get_kraj_from_text(normalize_text(clean_loc), obce_list)
        if target_kraj_norm == "hlavni mesto praha": display_kraj = "Hlavní Město Praha"
        elif target_kraj_norm == "Neznamy": display_kraj = "Neznámý"
        else: display_kraj = f"{target_kraj_norm.replace(' kraj', '').strip().title()} kraj"

        regional_stats[display_kraj] = regional_stats.get(display_kraj, 0) + 1

        data_pro_html.append({
            '#': idx, 'Inzerát': loc, 'Vzdálenost (km)': dist_val,
            'Operátor': op_name, 'Makléř': agent_name, 'Kontakt': phone_map.get(clean_loc, ""),
            'Odkaz': f'<a href="{ad_url}" target="_blank">Otevřít</a>' if ad_url else "-"
        })

        if op_name not in operator_assignments: operator_assignments[op_name] = []
        operator_assignments[op_name].append(item['text'])

    # Příprava HTML tabulky krajů
    df_regions = pd.DataFrame(list(regional_stats.items()), columns=['Kraj', 'Počet inzerátů'])
    df_regions = df_regions.sort_values(by='Počet inzerátů', ascending=False)
    regions_table_html = df_regions.to_html(escape=False, index=False, classes='pure-table')

    prague_tz = pytz.timezone('Europe/Prague')
    aktualizace_str = datetime.now(prague_tz).strftime('%d.%m.%Y %H:%M:%S')
    map_html = m._repr_html_()
    table_html = pd.DataFrame(data_pro_html).to_html(escape=False, index=False, classes='pure-table')

    # Sestavení HTML
    full_html = f"""<html><head><meta charset='utf-8'><style>
    body {{ font-family: 'Segoe UI', sans-serif; margin: 0; padding: 0; background: #f0f2f5; }}
    #lock-screen {{ position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: rgba(240, 242, 245, 0.8); z-index: 9999; display: flex; align-items: center; justify-content: center; backdrop-filter: blur(10px); }}
    .lock-box {{ background: white; padding: 30px; border-radius: 12px; box-shadow: 0 10px 25px rgba(0,0,0,0.1); text-align: center; }}
    #main-content {{ filter: blur(20px); transition: filter 0.5s ease; padding: 20px; }}
    .container {{ max-width: 1200px; margin: 0 auto; display: flex; flex-direction: column; gap: 25px; }}
    .card {{ background: white; padding: 20px; border-radius: 12px; box-shadow: 0 4px 6px rgba(0,0,0,0.05); margin-bottom: 20px; clear: both; }}
    .map-container {{ height: 600px; width: 100%; overflow: hidden; border-radius: 8px; }}
    table {{ width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 14px; }}
    th {{ background-color: #0078d4; color: white; padding: 12px; text-align: left; }}
    td {{ padding: 12px; border-bottom: 1px solid #eee; }}
    .btn {{ display: inline-block; padding: 10px 15px; border-radius: 6px; text-decoration: none; font-weight: bold; cursor: pointer; border: none; font-size: 14px; }}
    .btn-wa {{ background: #25D366; color: white; }}
    .btn-copy {{ background: #0078d4; color: white; }}
    input[type='password'] {{ padding: 10px; border: 1px solid #ddd; border-radius: 5px; margin-bottom: 10px; width: 200px; }}
    </style>
    <script>
    const allowed = {valid_passwords};
    function checkPassword() {{
        const val = document.getElementById('pass').value.toLowerCase().normalize('NFD').replace(/[\\u0300-\\u036f]/g, "");
        if (allowed.includes(val)) {{
            document.getElementById('lock-screen').style.display = 'none';
            document.getElementById('main-content').style.filter = 'none';
        }} else {{ alert('Chybné heslo!'); }}
    }}
    function downloadOpText(opId) {{
        const text = document.getElementById('txt_' + opId).value;
        const blob = new Blob([text], {{ type: 'text/plain;charset=utf-8' }});
        const link = document.createElement('a');
        link.href = URL.createObjectURL(blob);
        link.download = 'zakazky_' + opId + '.txt';
        link.click();
    }}
    </script>
    </head><body>
    <div id='lock-screen'><div class='lock-box'><h3>🔒 Přístup omezen</h3><p>Zadej heslo :</p><input type='password' id='pass' onkeydown='if(event.key==="Enter") checkPassword()'><br><button class='btn btn-copy' onclick='checkPassword()'>Vstoupit</button></div></div>
    <div id='main-content'><div class='container'>
        <div style='text-align:center;'><h2>Přehled realitní inzerce</h2><p>Aktualizováno: {aktualizace_str}</p></div>
        <div class='card'><h3>📱 Sekce pro operátory</h3><div style='display:flex; flex-wrap:wrap; gap:15px;'>"""

    for op, texts in sorted(operator_assignments.items()):
        combined_text = "\n\n".join([f"{i+1}. {t}" for i, t in enumerate(texts)])
        wa_url = f"https://wa.me/?text={urllib.parse.quote(combined_text)}"
        safe_op = op.replace(' ', '_')
        full_html += f"""
        <div style='border:1px solid #ddd; padding:15px; border-radius:8px; background:#fafafa; flex:1; min-width:250px;'>
            <h4 style='margin-top:0;'>👤 {op}</h4>
            <p>Zakázek: {len(texts)}</p>
            <a href=\"{wa_url}\" target=\"{wa_url}\" class=\"btn btn-wa\" style='display:block; margin-bottom:5px; text-align:center;'>WhatsApp</a>
            <button onclick=\"downloadOpText('{safe_op}')\" class=\"btn btn-copy\" style='display:block; width:100%;'>Stáhnout TXT</button>
            <textarea id=\"txt_{safe_op}\" style=\"display:none;\">{combined_text}</textarea>
        </div>"""

    full_html += f"""</div></div>
        <div class='card'><h3>📍 Mapa zakázek</h3><div class='map-container'>{map_html}</div></div>
        <div class='card'><h3>📋 Seznam unikátních inzerátů</h3>{table_html}</div>
        <div class='card'><h3>🌍 Souhrn unikátních inzerátů dle krajů</h3>{regions_table_html}</div>
        </div></div></body></html>"""

    filename = 'Dashboard.html'
    with open(filename, 'w', encoding='utf-8') as f: f.write(full_html)
    print(f"✅ Dashboard.html lokalne vytvoren.")

    # --- 2. GitHub Export ---
    try:
        token = userdata.get('github_api') or userdata.get('GITHUB')
        if token:
            repo_owner, repo_name = "DNA2026", "HVB"
            if os.path.exists(repo_name): shutil.rmtree(repo_name)
            repo_url = f"https://{token}@github.com/{repo_owner}/{repo_name}.git"
            print(f"Exportuji na GitHub: {repo_owner}/{repo_name}...")

            if os.system(f'git clone {repo_url}') == 0:
                shutil.copy(filename, os.path.join(repo_name, filename))
                os.chdir(repo_name)
                os.system('git config --global user.email "bot@hvbreal.cz"')
                os.system('git config --global user.name "HVB Bot"')
                os.system(f'git add {filename}')
                os.system(f'git commit -m "Auto-update dashboard: {aktualizace_str}"')
                if os.system(f'git push {repo_url} main') != 0:
                    os.system(f'git push {repo_url} master')
                os.chdir('..')
                print("✅ Dashboard byl úspěšně exportován na GitHub.")
            else: print("❌ Chyba pri klonovani repozitare.")
        else: print("⚠️ GitHub token nenalezen v Secrets.")
    except Exception as e: print(f"❌ Chyba GitHub: {e}")

"""Ranní email"""

import smtplib
import os
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
from datetime import datetime
import pandas as pd
import re

def get_secret(key):
    val = os.environ.get(key)
    if val: return val
    try:
        from google.colab import userdata
        val = userdata.get(key)
        if val: return val
    except Exception: pass
    return None

def odeslat_automatically_report():
    try:
        sender_email = get_secret('GMAIL_SENDER')
        target_email = get_secret('GMAIL_USER')
        app_password = get_secret('GMAIL_APP_PASSWORD')
        copy_email = get_secret('GMAIL_SENDER_COPY')

        if not all([sender_email, target_email, app_password]):
            print("⚠️ E-mailové klíče nebyly nalezeny.")
            return

        # --- Statistiky operátorek ---
        op_stats = {}
        unique_ads_texts = set()
        dedup_final_vystup = []

        if 'final_vystup_raw' in globals():
            for item in final_vystup_raw:
                fingerprint = str(item['row']['Inzerát']).strip()
                if fingerprint not in unique_ads_texts:
                    unique_ads_texts.add(fingerprint)
                    dedup_final_vystup.append(item)
                    op_name = item['op']
                    op_stats[op_name] = op_stats.get(op_name, 0) + 1

        total = len(blocks) if 'blocks' in globals() else 0
        exported = len(dedup_final_vystup)
        datum = datetime.now().strftime('%d.%m.%Y')

        # --- Regionální statistiky ---
        email_geo_stats = {}
        assigned_regions = set()
        for item in dedup_final_vystup:
            loc_line = str(item['row']['Inzerát']).strip()
            target_kraj_norm = get_kraj_from_text(normalize_text(loc_line), obce_list)

            if target_kraj_norm == "hlavni mesto praha": display_kraj = "Hlavní Město Praha"
            elif target_kraj_norm == "Neznamy": display_kraj = "Neznámý"
            else: display_kraj = f"{target_kraj_norm.replace(' kraj', '').strip().title()} kraj"

            assigned_regions.add(display_kraj)
            email_geo_stats[display_kraj] = email_geo_stats.get(display_kraj, 0) + 1

        count_regions_with_ads = len([k for k in assigned_regions if k != "Neznámý"])
        kraj_utilization = (count_regions_with_ads / 14) * 100

        out_of_reach = 0
        if 'filtered_out_info' in globals():
            for item in filtered_out_info:
                d = str(item.get('Důvod', '')).lower()
                if any(x in d for x in ['mimo dosah', 'žádný agent', 'limit']):
                    out_of_reach += 1

        duplicities = max(0, total - exported - out_of_reach)
        denom = (total - duplicities)
        success_rate = (exported / denom * 100) if denom > 0 else 0
        system_utilization = (success_rate * kraj_utilization) / 100

        op_html = "".join([f"<li>{op}: <b>{count} inzerátů</b></li>" for op, count in sorted(op_stats.items())])
        agent_html = "".join([f"<li>{name}: <b>{count}</b></li>" for name, count in sorted(assigned_counts.items(), key=lambda x: x[1], reverse=True)])

        inzerce_html = ""
        sorted_email_stats = sorted(email_geo_stats.items(), key=lambda x: x[1], reverse=True)
        for display_kraj, val in sorted_email_stats:
            if val > 0:
                inzerce_html += f"<tr><td style='padding:5px; border-bottom:1px solid #eee;'>{display_kraj}</td><td style='padding:5px; border-bottom:1px solid #eee; text-align:right;'><b>{val}</b></td></tr>"

        html_content = f"""
        <html>
        <body style='font-family: Arial, sans-serif; color: #333;'>
            <h2 style='color: #0078d4;'>Ranní report {datum}</h2>
            <div style='background: #f8f9fa; padding: 15px; border-radius: 8px;'>
                <h3>📊 Hlavní statistiky</h3>
                <ul>
                    <li>Celkový počet inzerátů: <b>{total}</b></li>
                    <li>Počet duplicitních inzerátů: <b>{duplicities}</b></li>
                    <li>Mimo dosah (nezařazeno): <b>{out_of_reach}</b></li>
                    <li>Úspěšně přiřazené (unikátní): <b>{exported}</b></li>
                    <li style='margin-top: 10px; font-weight: bold; border-top: 1px solid #ccc; padding-top: 5px;'>Úspěšnost přiřazení: <span style='color: #0078d4;'>{success_rate:.1f}%</span></li>
                    <li>Vytížení krajů: <b>{kraj_utilization:.1f}%</b> ({count_regions_with_ads}/14)</li>
                    <li style='background: #fff3cd; padding: 5px;'>Vytížení systému: <b>{system_utilization:.1f}%</b></li>
                </ul>
            </div>
            <h3>👧 Rozdělení dle operátorek</h3>
            <ul>{op_html}</ul>
            <h3>💼 Vytížení makléřů</h3>
            <ul>{agent_html}</ul>
            <h3>📍 Detailní inzerce dle krajů</h3>
            <table style='width: 100%; max-width: 400px; border-collapse: collapse;'>
                <thead><tr style='background:#eee;'><th style='text-align:left; padding:5px;'>Kraj</th><th style='text-align:right; padding:5px;'>Inzeráty</th></tr></thead>
                <tbody>{inzerce_html}</tbody>
            </table>
            <p style='margin-top:20px;'><a href='https://dna2026.github.io/HVB/Dashboard.html' style='background:#0078d4; color:white; padding:10px 15px; text-decoration:none; border-radius:5px;'>Otevřít interaktivní Dashboard</a></p>
            <p><i>Poznámka: Podrobný rozpis duplicit naleznete v přiloženém souboru Duplicity.html.</i></p>
        </body>
        </html>
        """

        msg = MIMEMultipart()
        msg['From'] = sender_email
        msg['To'] = target_email
        if copy_email:
            msg['Cc'] = copy_email
        msg['Subject'] = f"Ranní report zpracování inzerce {datum}"
        msg.attach(MIMEText(html_content, 'html'))

        if os.path.exists('Duplicity.html'):
            with open('Duplicity.html', 'rb') as attachment:
                part = MIMEBase('application', 'octet-stream')
                part.set_payload(attachment.read())
                encoders.encode_base64(part)
                part.add_header('Content-Disposition', "attachment; filename=Duplicity.html")
                msg.attach(part)

        # --- Oprava doručení kopie ---
        recipients = [target_email]
        if copy_email:
            recipients.append(copy_email)

        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(sender_email, app_password)
        server.sendmail(sender_email, recipients, msg.as_string())
        server.quit()
        print(f"✅ Report odeslán na {target_email}" + (f" a v kopii na {copy_email}." if copy_email else "."))
    except Exception as e:
        print(f"❌ Chyba: {e}")

odeslat_automatically_report()