name: Automatizace OCTO

on:
  schedule:
    # Běží v 14:00 UTC (16:00 našeho času) pouze v pondělí, úterý, středu, čtvrtek a pátek (1-5)
    - cron: '0 14 * * MON-FRI'
  workflow_dispatch: # Tlačítko pro ruční spuštění

permissions:
  contents: write

jobs:
  run-octo:
    runs-on: ubuntu-latest
    steps:
      - name: Stazeni kodu z GitHubu
        uses: actions/checkout@v4

      - name: Nastaveni Pythonu a knihoven
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install pandas requests openrouteservice gdown

      - name: Priprava souboru z Google Disku a Tokenu
        run: |
          # 1. Stáhne soubor z Disku (Nahraď TVE_ID_SOUBORU skutečným ID)
          gdown --id TVE_ID_SOUBORU -O nazev_souboru_z_disku.csv
          
          # 2. Vytvoří textový soubor s tokenem pro OpenRouteService
          echo "${{ secrets.OPENROUTESERVICE_TOKEN }}" > ors_token.txt

      - name: Spusteni Python skriptu OCTO
        run: python OCTO.py

      - name: Ulozeni vygenerovaneho HTML na GitHub
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add index.html # Změň název, pokud se HTML jmenuje jinak
          git diff --quiet && git diff --staged --quiet || (git commit -m "Aktualizace webu z OCTO.py" && git push)
